---
paths:
  /api/metrics:
    get:
      parameters: []
      responses:
        "200":
          description: "default response"
          content:
            text/plain:
              schema:
                type: "string"
        default:
          description: "default response"
          content:
            text/plain:
              schema:
                type: "string"
      operationId: "getText_1_2"
  /api/metrics/{registry}/{metric}:
    get:
      parameters:
      - schema:
          type: "string"
        required: true
        style: "simple"
        in: "path"
        name: "registry"
      - schema:
          type: "string"
        required: true
        style: "simple"
        in: "path"
        name: "metric"
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
      operationId: "getJson_1"
    options:
      parameters:
      - schema:
          type: "string"
        required: true
        style: "simple"
        in: "path"
        name: "registry"
      - schema:
          type: "string"
        required: true
        style: "simple"
        in: "path"
        name: "metric"
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
      operationId: "getMetadata_1"
  /api/metrics/{registry}:
    get:
      parameters:
      - schema:
          type: "string"
        required: true
        style: "simple"
        in: "path"
        name: "registry"
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
      operationId: "getJson_1_2"
    options:
      parameters:
      - schema:
          type: "string"
        required: true
        style: "simple"
        in: "path"
        name: "registry"
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
      operationId: "getMetadata"
  /api/health:
    get:
      parameters: []
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                nullable: true
                properties: {}
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                nullable: true
                properties: {}
      operationId: "getChecks"
  /api/async/touchpoints/{id}: {}
  /api/async/touchpoints: {}
  /api/opi/touchpoints/{id}:
    get:
      parameters:
      - schema:
          type: "integer"
        required: true
        style: "simple"
        in: "path"
        name: "id"
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/StationaryTouchpoint"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/StationaryTouchpoint"
      operationId: "readTouchpoint"
    delete:
      parameters:
      - schema:
          type: "integer"
        required: true
        style: "simple"
        in: "path"
        name: "id"
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "boolean"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "boolean"
      operationId: "deleteTouchpoint"
  /api/opi/touchpoints:
    get:
      parameters: []
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  $ref: "#/components/schemas/StationaryTouchpoint"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  $ref: "#/components/schemas/StationaryTouchpoint"
      operationId: "readAllTouchpoints"
    post:
      parameters: []
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/StationaryTouchpoint"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/StationaryTouchpoint"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              $ref: "#/components/schemas/StationaryTouchpoint"
      operationId: "createTouchpoint"
  /api/opi/products/{productId}:
    get:
      parameters:
      - schema:
          type: "integer"
        required: true
        style: "simple"
        in: "path"
        name: "productId"
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
      operationId: "readProduct"
    delete:
      parameters:
      - schema:
          type: "integer"
        required: true
        style: "simple"
        in: "path"
        name: "productId"
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "boolean"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "boolean"
      operationId: "deleteProduct"
    put:
      parameters:
      - schema:
          type: "integer"
        required: true
        style: "simple"
        in: "path"
        name: "productId"
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              $ref: "#/components/schemas/IndividualisedProductItem"
      operationId: "updateProduct"
  /api/opi/products/campaign:
    post:
      parameters: []
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/Campaign"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/Campaign"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              $ref: "#/components/schemas/Campaign"
      operationId: "createCampaign"
  /api/opi/products:
    get:
      parameters: []
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  $ref: "#/components/schemas/IndividualisedProductItem"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  $ref: "#/components/schemas/IndividualisedProductItem"
      operationId: "readAllProducts"
    post:
      parameters: []
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              $ref: "#/components/schemas/IndividualisedProductItem"
      operationId: "createProduct"
info:
  version: "0.1"
  description: ""
  license:
    url: ""
    name: ""
  termsOfService: ""
  title: "WebAPI for JRS, OPI and WSV exercises"
  contact:
    url: ""
    email: ""
    name: ""
components:
  schemas:
    java_lang_Object:
      type: "object"
      properties: {}
    StationaryTouchpoint:
      type: "object"
      properties:
        address:
          type: "object"
          $ref: "#/components/schemas/Address"
        erpPointOfSaleId:
          type: "integer"
        name:
          type: "string"
        id:
          type: "integer"
        customers:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_Customer"
        transactions:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_CustomerTransaction"
    Address:
      type: "object"
      properties:
        zipCode:
          type: "string"
        city:
          type: "string"
        street:
          type: "string"
        geoLong:
          type: "integer"
        geoLat:
          type: "integer"
        id:
          type: "integer"
        houseNr:
          type: "string"
    org_dieschnittstelle_ess_entities_crm_Customer:
      type: "object"
      properties:
        lastName:
          type: "string"
        firstName:
          type: "string"
        address:
          type: "object"
          $ref: "#/components/schemas/Address"
        gender:
          type: "string"
          nullable: true
          enum:
          - "M"
          - "W"
        touchpoints:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/AbstractTouchpoint"
        mobilePhoneId:
          type: "string"
        id:
          type: "integer"
        transactions:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_CustomerTransaction"
        email:
          type: "string"
        preferredTouchpoint:
          type: "object"
          $ref: "#/components/schemas/AbstractTouchpoint"
    org_dieschnittstelle_ess_entities_crm_CustomerTransaction:
      type: "object"
      properties:
        date:
          type: "string"
          nullable: true
        completed:
          type: "boolean"
        id:
          type: "integer"
        items:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_ShoppingCartItem"
        touchpoint:
          type: "object"
          $ref: "#/components/schemas/AbstractTouchpoint"
        value:
          type: "integer"
        customer:
          type: "object"
          $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_Customer"
    org_dieschnittstelle_ess_entities_crm_ShoppingCartItem:
      type: "object"
      properties:
        productObj:
          type: "object"
          $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_erp_AbstractProduct"
        erpProductId:
          type: "integer"
        campaign:
          type: "boolean"
        units:
          type: "integer"
        id:
          type: "integer"
    org_dieschnittstelle_ess_entities_erp_AbstractProduct:
      type: "object"
      properties:
        price:
          type: "integer"
        name:
          type: "string"
        id:
          type: "integer"
    AbstractTouchpoint:
      type: "object"
      properties:
        erpPointOfSaleId:
          type: "integer"
        name:
          type: "string"
        id:
          type: "integer"
        customers:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_Customer"
        transactions:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_CustomerTransaction"
    IndividualisedProductItem:
      type: "object"
      properties:
        price:
          type: "integer"
        name:
          type: "string"
        expirationAfterStocked:
          type: "integer"
        id:
          type: "integer"
        productType:
          type: "string"
          nullable: true
          enum:
          - "BREAD"
          - "ROLL"
          - "PASTRY"
    Campaign:
      type: "object"
      properties:
        price:
          type: "integer"
        bundles:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/ProductBundle"
        name:
          type: "string"
        id:
          type: "integer"
    ProductBundle:
      type: "object"
      properties:
        product:
          type: "object"
          $ref: "#/components/schemas/IndividualisedProductItem"
        units:
          type: "integer"
        id:
          type: "integer"
openapi: "3.0.1"
